export { crearDeck } from './crear-deck'
export { pedirCarta } from './pedir-carta'
export { valorCarta } from './valor-carta'
export { crearAlerta } from './crear-alerta'
export { limpiarHTML } from './limpiar-html'